# -*- coding: utf-8 -*-
"""audio_to_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8wvZdStWn1xJ4t9xSb7tlL1ifrnZ0k2
"""

import whisper
import tempfile

# Load Whisper model (use 'base' or 'small' for faster inference)
model = whisper.load_model("base")

def transcribe_audio(audio_file):
    """
    Converts uploaded audio file to text using Whisper
    :param audio_file: UploadedFile from Streamlit
    :return: Transcribed text (string)
    """
    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as tmp:
        tmp.write(audio_file.read())
        tmp_path = tmp.name

    result = model.transcribe(tmp_path)
    return result["text"]



