# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a8wvZdStWn1xJ4t9xSb7tlL1ifrnZ0k2
"""

import streamlit as st
from utils.audio_to_text import transcribe_audio
from models.summarizer import summarize_text
from models.keyword_extractor import extract_keywords
from models.quiz_generator import generate_questions
from models.difficulty_predictor import predict_difficulty

st.set_page_config(page_title="Lecture Summarizer", layout="wide")

st.title("🎓 ML-Powered Lecture Summarizer")

uploaded_file = st.file_uploader("Upload Lecture Audio or Transcript", type=["mp3", "wav", "txt"])

if uploaded_file:
    if uploaded_file.name.endswith(".txt"):
        raw_text = uploaded_file.read().decode("utf-8")
    else:
        st.info("⏳ Transcribing audio... please wait.")
        raw_text = transcribe_audio(uploaded_file)

    st.subheader("📜 Raw Transcript")
    st.text_area("", raw_text, height=250)

    st.subheader("📝 Summary")
    summary = summarize_text(raw_text)
    st.success(summary)

    st.subheader("📌 Key Topics")
    keywords = extract_keywords(summary)
    st.write(keywords)

    st.subheader("🧠 Predicted Difficulty")
    difficulty = predict_difficulty(summary)
    st.metric(label="Difficulty Level", value=difficulty)

    st.subheader("❓ Auto-Generated Questions")
    questions = generate_questions(summary)
    for q in questions:
        st.write(f"- {q}")



