# -*- coding: utf-8 -*-
"""quiz_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y4OeyVZly1MhAgl4QQMlUPcnXZwbKEci
"""

import random

def generate_questions(summary):
    # Very simple: turn sentences into WH-questions
    questions = []
    sentences = summary.split('. ')
    for sentence in sentences:
        if "is" in sentence or "are" in sentence:
            q = sentence.replace(" is ", " What is ").replace(" are ", " What are ")
            questions.append(q + "?")
    return random.sample(questions, min(5, len(questions)))

