# -*- coding: utf-8 -*-
"""summerizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RAxAgTBTPWeFRcfhRHV6jmOJlyk9Mac5
"""

from transformers import pipeline

# Load T5 or BART summarizer from Hugging Face
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

def summarize_text(text):
    max_chunk = 500
    chunks = [text[i:i+max_chunk] for i in range(0, len(text), max_chunk)]
    res = []
    for chunk in chunks:
        out = summarizer(chunk, max_length=120, min_length=30, do_sample=False)
        res.append(out[0]['summary_text'])
    return " ".join(res)

